Presences
MWO-team2/StudentPanel pull request #21
Opened 2018-05-09 14:38 UTC by bockowsk

Closes #18

2018-05-12 09:09 UTC, Yankowski requested changes
Everythins looks ok, the calendar looks great, please remove unused improts and it is ready to merge, do not pay attention on previous commits becasue as far as i see this was resolved in the latest commits.

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/entity/Presence.java
> +	/*@Column(name = "date")
remove commented line

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/entity/Presence.java
> +
remove uneccesary lines

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/entity/Presence.java
>  import javax.persistence.FetchType;
remove unused imports

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/controller/PresenceController.java
> +/*    @RequestMapping(value = "/AddSubject")
remove commented code

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/controller/PresenceController.java
> +/*
remove commented code

2018-05-12 09:09 UTC, Yankowski commented on src/main/java/pl/edu/agh/ki/mwo/SchoolWebApp/controller/PresenceController.java
remove unused imports

2018-05-15 10:45 UTC, bockowsk commented
ok, a new commit with some cleaning

2018-05-24 09:40 UTC, merged